### ISSUE TITLE
Incompatibilidade SinonJS

### ISSUE THREAD

**Issue by matheus-souza** [waldemarnt/building-testable-apis-with-nodejs#14]
Primeiramente, parabéns pela iniciativa, pelo seu trabalho, tanto o livro como os videos.
Só vim alertar que se utilizar apenas `npm install --save-dev sinon` como sugere no livro o sinon-as-promised não funciona corretamente, pois o npm pega a ultima pre-release do Sinon que é a versão 2.0.0 e o teste acaba não passando. Este erro pode ser facilmente corrigido se forçar na hora de instalar a versão 1.17.2 do Sinon.

Abraços, camigo, camigol, camigol!

**Comment by juliafealves** [comment]
Realmente, isto também aconteceu comigo. Corrigi olhando o package.json do projeto do livro.

Abraços.

**Comment by matheus-souza** [comment]
Sim, também arrumei olhando o package.json, mas vim deixei aqui só para que em novas versões isso possa ser ajustado.

Abraços

**Comment by waldemarnt** [comment]
Vou revisar, obrigado por reportar

**Comment by waldemarnt** [comment]
Galera, muito obrigado! ja arrumei como podem ver aqui https://github.com/waldemarnt/building-testable-apis-with-nodejs-code/pull/10
Vou atualizar o livro agora. Por favor usem a 2.x
