### ISSUE TITLE
Referência externa com nome do autor errado

### ISSUE THREAD

**Issue by cantoniazzi** [waldemarnt/building-testable-apis-with-nodejs#23]
O sobrenome do autor do paper _"Ajax: A New Approach to Web Applications"_ é na verdade Garrett (terminando com dois t's) e não Garreth (terminando com th).

Criei um PR corrigindo este pequeno problema. \o

https://github.com/waldemarnt/building-testable-apis-with-nodejs/pull/22

**Comment by waldemarnt** [comment]
Valeu! O PR ja foi mergeado
