### ISSUE TITLE
JWT no Ebook?

### ISSUE THREAD

**Issue by winiciuslima** [waldemarnt/building-testable-apis-with-nodejs#4]
Olá gostaria de tirar uma dúvida, mas desde antes gostaria de parabenizar pelo trabalho.
A dúvida é a seguinte:
Você vai ensinar como efetuar a autenticação JWT na API ensinada no livro? 
Gostaria de saber isso pois vejo que esse tipo de autenticação é bastante usado em aplicações Node.js.

Abraços

**Comment by waldemarnt** [comment]
Oi @winiciuslima sim, tera mais de um capitulo falando de autenticação e também autorização utilizando JWT com roles e etc.

Obrigado pelo feedback 👍

**Comment by waldemarnt** [comment]
@winiciuslima o livro foi adicionado e possui examplos de JWT 💃
