### ISSUE TITLE
Continuidade com Docker

### ISSUE THREAD

**Issue by EdZava** [waldemarnt/building-testable-apis-with-nodejs#6]
Seria legal se continuasse no livro com uma parte de DevOps.
Talvez usando docker e adicionando na api o uso de mais de uma DB. ex: mongo.db y postgresql e como fazer o deploy de tudo isso.

**Comment by waldemarnt** [comment]
Opa Ed, cara tenho ideia de por algo relacionado a isso sim, tanto que ja lancei algum conteudo pra validar essa ideia, se quiser dar uma olhada: http://walde.co/2016/08/30/tudo-que-voce-precisa-saber-para-rodar-sua-aplicacao-nodejs-com-docker/
